# Generated by Django 2.1.15 on 2021-12-14 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20211214_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.SmallIntegerField(default='2021', verbose_name='Год выпуска'),
        ),
    ]
